### PR TITLE
Release candidate 1.0.0

### PR DESCRIPTION
**Pull request by newhouse**

### CODE REVIEW

**Comment by JeromeErasmus** [comment]
Had a quick play around with this branch which looks exciting.

There was the below error been generated when using introspection and running the below command

```
yarn spectaql ./docs/config.specaql.yml -t ./docs/public/
```

```

/Users/jerome/dev/mustang/drive-boot/app/node_modules/graphql/utilities/buildClientSchema.js:119
      throw new Error("Invalid or incomplete schema, unknown type: ".concat(typeName, ". Ensure that a full introspection query is used in order to build a client schema."));
      ^

Error: Invalid or incomplete schema, unknown type: Mutation. Ensure that a full introspection query is used in order to build a client schema.
    at getNamedType (/Users/jerome/dev/mustang/drive-boot/app/node_modules/graphql/utilities/buildClientSchema.js:119:13)
    at getObjectType (/Users/jerome/dev/mustang/drive-boot/app/node_modules/graphql/utilities/buildClientSchema.js:126:46)
    at buildClientSchema (/Users/jerome/dev/mustang/drive-boot/app/node_modules/graphql/utilities/buildClientSchema.js:67:57)
    at graphQLSchemaFromIntrospectionResponse (/Users/jerome/dev/mustang/drive-boot/app/node_modules/spectaql/dist/spectaql/graphql-loaders.js:128:41)
    at buildSchemas (/Users/jerome/dev/mustang/drive-boot/app/node_modules/spectaql/dist/spectaql/build-schemas.js:126:84)
    at run (/Users/jerome/dev/mustang/drive-boot/app/node_modules/spectaql/dist/spectaql/index.js:44:33)
    at _loadData (/Users/jerome/dev/mustang/drive-boot/app/node_modules/spectaql/dist/index.js:161:10)
    at run (/Users/jerome/dev/mustang/drive-boot/app/node_modules/spectaql/dist/index.js:179:59)
    at Object.<anonymous> (/Users/jerome/dev/mustang/drive-boot/app/node_modules/spectaql/bin/spectaql.js:7:1)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:60:12)
    at internal/main/run_main_module.js:17:47

error Command failed with exit code 1.
```

**Comment by newhouse** [comment]
@JeromeErasmus this is likely due to something that [`microfiber`](https://www.npmjs.com/package/microfiber) is doing to your introspection query results. Can you provide:
1) Your `config.spectaql.yml` (or its contents)
2) A (preferably minimal) Introspection Query Result or SDL that you're using that would cause this error to occur?

**Comment by JeromeErasmus** [comment]
Yep I'll do some more testing on my side.

Let me know what I can do to help to you get this PR closer to approval for you

**Comment by mxxnhxTW** [comment]
Hi, I'm taking a look this branc to use newly added feature, which is GraphQL subscription documenting support.

I'm not sure the below changes are intended in current PR, but anyway this codes make an error when taking gql from url in introspection option.

In `src/index.js`, the below code also normalizes introspection > url options also whatever the url string starts with.
```js
function resolvePaths(
  options,
  keys = [
    'targetDir',
    'appDir',
    'logoFile',
    'additionalJsFile',
    'additionalCssFile',
    'faviconFile',
    'specFile',
    'gruntConfigFile',
  ]
) {
  keys.forEach((key) => {
    const pth = options[key]
    if (typeof pth === 'string') {
      options[key] = normalizePath(pth)
    }
  })
}
```

For example, I put my server url starting with https://, but after `resolvePaths` functions is called on line 181 in `src/index.js`, the url was chaned `/home/username/spectaql/http:/...`.

At least for me, this isn't desired. 
I hope this situation will help you to make a release safely. 

Anyway, I'm really appreciating for you to develop this awesome open source for auto-generated document for GraphQL API. 👍

**Comment by newhouse** [comment]
> Yep I'll do some more testing on my side.

@JeromeErasmus 

I think this was a bug in `microfiber` that I have now fixed. Please try the latest stuff.

**Comment by newhouse** [comment]
> For example, I put my server url starting with https://, but after `resolvePaths` functions is called on line 181 in `src/index.js`, the url was chaned `/home/username/spectaql/http:/...`.

@mxxnhxTW this has been fixed now in this branch. Please try again, and thanks for pointing this out! 

> Anyway, I'm really appreciating for you to develop this awesome open source for auto-generated document for GraphQL API. 👍

Thanks!

**Comment by benogle** [comment]
💥

**Pull request merged**
